version: '3'
services:
    frontend:
        build:
            context: ./frontend
        container_name: c42759-frontend
        restart: unless-stopped
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - '${APP_FRONTEND_PATH}:/app'
            - './docs:/app/build'
            - './logs/frontend:/root/.npm/_logs/'
        command: ./run_server.sh
        ports:
            - '${REACT_EXPOSE_PORT}:3000'
