name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux, ubuntu-latest]
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: pnpm install
      - run: pnpm run build --if-present
      - run: pnpm test
